/*
 *
 *  * Copyright (C) 2024 Pavel Korzh
 *  * SPDX-License-Identifier: GPL-3.0-only
 *
 */
def scriptName = System.getProperty('os.name').toLowerCase().contains('win') ? 'run.bat' : 'run.sh'
def scriptPath = file("$rootDir/distro/$scriptName")
tasks.register('counters') {
    group = 'examples'
    dependsOn tasks.named('assemble')
    doLast {
        exec {
            workingDir "$rootDir/stuff/examples/counters"
            executable scriptPath
            args 'counters.net'
        }
    }
}
tasks.register('z80') {
    group = 'examples'
    dependsOn tasks.named('assemble')
    doLast {
        exec {
            workingDir "$rootDir/stuff/examples/z80"
            executable scriptPath
            args 'z80.net'

        }
    }
}
tasks.register('clock') {
    group = 'examples'
    dependsOn tasks.named('assemble')
    doLast {
        exec {
            workingDir "$rootDir/stuff/examples/clock"
            executable scriptPath
            args 'clock.net'

        }
    }
}
tasks.register('trs80') {
    group = 'examples'
    dependsOn tasks.named('assemble')
    doLast {
        exec {
            workingDir "$rootDir/stuff/examples/trs80"
            executable scriptPath
            args "TRS80I.net"

        }
    }
    dependsOn tasks.named('downloadCharGenBin')
    dependsOn tasks.named('downloadRomA')
    dependsOn tasks.named('downloadRomB')
}
tasks.register("downloadCharGenBin") {
    doLast {
        apply from: "$rootDir/gradle/utils.gradle"
        project.ext.downloadFileIfNotExists(
                "https://raw.githubusercontent.com/RetroStack/Character_Generator_ROMs/main/TRS-80%20Model%201/Individual/character_set_10.bin",
                file("$rootDir/stuff/examples/trs80/character_set_10.bin")
        )
    }
}
tasks.register("downloadRomA") {
    doLast {
        apply from: "$rootDir/gradle/utils.gradle"
        project.ext.downloadFileIfNotExists(
                "https://raw.githubusercontent.com/RetroStack/TRS-80-Model-I-System-ROMs/refs/heads/main/1-Option_2x64/rom_a_L2_v13.bin",
                file("$rootDir/stuff/examples/trs80/rom_a_L2.bin")
        )
    }
}
tasks.register("downloadRomB") {
    doLast {
        apply from: "$rootDir/gradle/utils.gradle"
        project.ext.downloadFileIfNotExists(
                "https://raw.githubusercontent.com/RetroStack/TRS-80-Model-I-System-ROMs/refs/heads/main/1-Option_2x64/rom_b_L2_v13.bin",
                file("$rootDir/stuff/examples/trs80/rom_b_L2.bin")
        )
    }
}
