/*
 *
 *  * Copyright (C) 2024 Pavel Korzh
 *  * SPDX-License-Identifier: GPL-3.0-only
 *
 */
//ToDo
// add filters:
//   similar interconnected inputs -> -1 input
//   or/and with 1 input -> repeater
//   repeater on power rail -> power
//   pull on strong only
// "not used" pin -> add "on power rail"

sourceSets {
    main {
        java {
            srcDirs = [] // Empty source directories list to disable Java source directory
        }
        resources {
            srcDirs = [] // Empty source directories list to disable resources directory
        }
    }
    test {
        java {
            srcDirs = [] // Empty source directories list to disable Java source directory
        }
        resources {
            srcDirs = [] // Empty source directories list to disable resources directory
        }
    }
}
dependencies {
    runtimeOnly project("and")
    runtimeOnly project("buffer")
    runtimeOnly project("busDriver")
    runtimeOnly project("counter")
    runtimeOnly project("dCounter")
    runtimeOnly project("dcTrigger")
    runtimeOnly project("decoder")
    runtimeOnly project("dipSwitch")
    runtimeOnly project("display")
    runtimeOnly project("jkTrigger")
    runtimeOnly project("keyboard")
    runtimeOnly project("led")
    runtimeOnly project("led7SegmentDisplay")
    runtimeOnly project("led16SegmentDisplay")
    runtimeOnly project("mos6502")
    runtimeOnly project("mos6532")
    runtimeOnly project("multiplexer")
    runtimeOnly project("or")
    runtimeOnly project("oscillator")
    runtimeOnly project("diode")
    runtimeOnly project("resister")
    runtimeOnly project("switch")
    runtimeOnly project("power")
    runtimeOnly project("ram")
    runtimeOnly project("repeater")
    runtimeOnly project("ringCounter")
    runtimeOnly project("rom")
    runtimeOnly project("sdram")
    runtimeOnly project("shifter")
    runtimeOnly project("stateMachine")
    runtimeOnly project("tester")
    runtimeOnly project("transistor")
    runtimeOnly project("xor")
    runtimeOnly project("z80")
}

tasks.named("jar") {
    onlyIf { false }
}

configure(subprojects) { subproject ->
    apply plugin: 'groovy'
    def copyToLibTask = rootProject.tasks.named("copyToLib")

    tasks.named("compileTestJava") {
        mustRunAfter copyToLibTask
    }

    tasks.named("compileTestGroovy") {
        mustRunAfter copyToLibTask
    }
    def libs = rootProject.libs
    sourceSets {
        test {
            java {
                srcDirs = ["test/java"]
            }
            groovy {
                srcDirs = ["test/groovy"]
            }
            resources {
                srcDirs = ["test/resources"]
            }
        }
    }
    tasks.register("bench", JavaExec) {
        group = 'Benchmark'
        description = 'Run JMH benchmarks'
        classpath = sourceSets.test.runtimeClasspath
        mainClass = 'org.openjdk.jmh.Main'
        // Optional: Set JVM arguments
        jvmArgs = [
                '--module-path', "$rootDir/distro/;$rootDir/distro/lib/;$rootDir/distro/schemaParts/",
                '--add-modules', "KiCadLogicalSchemeSimulator.simulator",
                '--add-exports', 'KiCadLogicalSchemeSimulator.simulator/pko.KiCadLogicalSchemeSimulator.net.bus=ALL-UNNAMED',
                '--add-exports', 'KiCadLogicalSchemeSimulator.simulator/pko.KiCadLogicalSchemeSimulator.net.wire=ALL-UNNAMED',
                '--add-exports', 'KiCadLogicalSchemeSimulator.simulator/pko.KiCadLogicalSchemeSimulator.parsers.net=ALL-UNNAMED',
                '--add-exports', 'KiCadLogicalSchemeSimulator.simulator/pko.KiCadLogicalSchemeSimulator.parsers.xml=ALL-UNNAMED',
                '--add-opens', 'java.base/java.lang=KiCadLogicalSchemeSimulator.simulator',
        ]
        args = [
                '-wi', '10', // Number of warm-up iterations
                '-w', '3', // time of warm-up iterations
                '-i', '10', // Number of iterations
                '-r', '3', // time of iterations
                '-f1', // Number of forks
                '-t1', // Number of threads
                "pko.KiCadLogicalSchemeSimulator.components.${project.name.toUpperCase()}.test.Benchmark.bench"//
        ]
    }
    def simulatorSourceSets = project(":simulator")
            .extensions
            .getByName("sourceSets")
    def simulatorRuntimeClasspath = simulatorSourceSets.main.runtimeClasspath
    dependencies {
        implementation project(":simulator")
        implementation libs.jakarta.api
        testImplementation files(simulatorSourceSets.test.output)
        testRuntimeOnly project(":simulator")
        testImplementation libs.jmh
        testAnnotationProcessor libs.jmh.annotations
    }
    tasks.named("jar") {
        destinationDirectory = file("$rootDir/distro/schemaParts")
        from(sourceSets.main.allSource) {
            include '**/*.java'  // Filter to include only Java files
        }
    }
    test {
        useJUnitPlatform()
        dependsOn rootProject.tasks.named("copyToLib")
        ignoreFailures = true
        testLogging {
            events "passed", "skipped", "failed"
        }
        doFirst {
            jvmArgs += [
                    '--module-path', simulatorRuntimeClasspath.asPath,
                    '--add-modules', 'KiCadLogicalSchemeSimulator.simulator',
                    '--add-exports', 'KiCadLogicalSchemeSimulator.simulator/pko.KiCadLogicalSchemeSimulator.parsers.net=ALL-UNNAMED',
                    '--add-exports', 'KiCadLogicalSchemeSimulator.simulator/pko.KiCadLogicalSchemeSimulator.parsers.xml=ALL-UNNAMED',
                    '--add-opens', 'java.base/java.lang=KiCadLogicalSchemeSimulator.simulator'
            ]
        }
    }
}
